# This file is part of SyntheticSun.

# SyntheticSun is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 3 of the License, or
# (at your option) any later version.

# SyntheticSun is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.

# You should have received a copy of the GNU General Public License along with SyntheticSun.  
# If not, see https://github.com/jonrau1/SyntheticSun/blob/master/LICENSE.
AWSTemplateFormatVersion: 2010-09-09
Description: Creates the baseline resources needed for SyntheticSun such as WAF, Kinesis, ES and MISP assets. Deploy this first.
Parameters:
  ApplicationLoadBalancerArn:
    Type: String
    Description: The ARN of the Application Load Balancer to attach the SyntheticSun WAF to
  Ec2KeyPair:
    Type: AWS::EC2::KeyPair::KeyName
    Description: Key pair for EC2 instance for SSH access
  MISPSecGroup:
    Type: AWS::EC2::SecurityGroup::Id
    Description: Security Group for MISP instance. Must allow HTTPS traffic and optionally SSH access from a trusted CIDR
  EndpointRouteTable:
    Type: String
    Description: Route table to attach the DynamoDB and S3 VPC Endpoints to. This should be a route table in the VPC you will specify below.
  MISPAmiId:
    Type: AWS::EC2::Image::Id
    Description: The AMI ID for MISP-Cloud in us-east-1. Change to one applicable for your Region, AMIs are availabe at MISP/misp-cloud GitHub
    Default: ami-0e0e49a00c1176d7d
  PublicSubnetId:
    Type: AWS::EC2::Subnet::Id
    Description: Public Subnet for the MISP instance. This subnet must have a route to an IGW to be considered public.
  SGVpcId:
    Type: AWS::EC2::VPC::Id
    Description: VPC ID to create the new security group in. Must be the same VPC that has your subnet.
  MISPInstanceTypeParameter: 
    Type: String
    Default: r5.xlarge
    Description: Instance type for the MISP instance. R or M series are preferred if you will be using multiple feeds
    AllowedValues: 
      - t2.medium
      - t2.large
      - t2.xlarge
      - t3.medium
      - t3.large
      - t3.xlarge
      - m4.large
      - m4.xlarge
      - m5.large
      - r4.large
      - r4.xlarge
      - m5.xlarge
      - r5.large
      - r5.xlarge
  ESVersion:
    Type: String
    Default: 7.4
    Description: The Elasticsearch version number to use for your Domain
    AllowedValues:
      - 7.4
      - 7.7
  ESDataNodeInstanceType: 
    Type: String
    Default: r5.large.elasticsearch
    Description: Instance type for Elasticsearch data nodes
    AllowedValues:
      - t2.small.elasticsearch
      - t2.medium.elasticsearch
      - m4.xlarge.elasticsearch
      - m5.large.elasticsearch
      - r4.large.elasticsearch
      - r4.xlarge.elasticsearch
      - m5.xlarge.elasticsearch
      - r5.large.elasticsearch
      - r5.xlarge.elasticsearch
  ESMasterNodeInstanceType: 
    Type: String
    Default: m5.large.elasticsearch
    Description: Instance type for Elasticsearch master nodes
    AllowedValues: 
      - t2.small.elasticsearch
      - t2.medium.elasticsearch
      - m4.xlarge.elasticsearch
      - m5.large.elasticsearch
      - r4.large.elasticsearch
      - r4.xlarge.elasticsearch
      - m5.xlarge.elasticsearch
      - r5.large.elasticsearch
      - r5.xlarge.elasticsearch
Resources:
  DynamoVPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties: 
      RouteTableIds: 
        - !Ref EndpointRouteTable
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.dynamodb'
      VpcEndpointType: Gateway
      VpcId: !Ref SGVpcId
  S3VPCEndpoint:
    Type: AWS::EC2::VPCEndpoint
    Properties: 
      RouteTableIds: 
        - !Ref EndpointRouteTable
      ServiceName: !Sub 'com.amazonaws.${AWS::Region}.s3'
      VpcEndpointType: Gateway
      VpcId: !Ref SGVpcId 
  ThreatIntelWAFv2IPBlacklist:
    Type: AWS::WAFv2::IPSet
    Properties: 
      Addresses: 
        - 130.25.10.158/32
      Description: Placeholder IP Set for MISP updates
      IPAddressVersion: IPV4
      Name: CTI-Blocklist-IPSet
      Scope: REGIONAL
  WAFv2WebACL:
    Type: AWS::WAFv2::WebACL
    Properties:
      Name: SyntheticSun-WACL
      Scope: REGIONAL
      Description: Web ACL for SyntheticSun IP Sets and AMRs
      DefaultAction:
        Allow: {}
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: ExampleWebACLMetric
      Rules:
        - Name: AWSManagedRulesCommonRuleSet
          Priority: 0
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: AWSManagedRulesCommonRuleSetMetric
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesCommonRuleSet
              ExcludedRules: []
        - Name: AWSManagedRulesKnownBadInputsRuleSet
          Priority: 1
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: AWSManagedRulesKnownBadInputsRuleSetMetric
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesKnownBadInputsRuleSet
              ExcludedRules: []
        - Name: AWSManagedRulesAmazonIpReputationList
          Priority: 2
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: AWSManagedRulesAmazonIpReputationListMetric
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesAmazonIpReputationList
              ExcludedRules: []
        - Name: AWSManagedRulesAnonymousIpList
          Priority: 3
          OverrideAction:
            None: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: AWSManagedRulesAnonymousIpListMetric
          Statement:
            ManagedRuleGroupStatement:
              VendorName: AWS
              Name: AWSManagedRulesAnonymousIpList
              ExcludedRules: []
        - Name: ThreatIntelIPBlacklist
          Priority: 4
          Action:
            Block: {}
          VisibilityConfig:
            SampledRequestsEnabled: true
            CloudWatchMetricsEnabled: true
            MetricName: IpBlacklistMetric
          Statement:
            IPSetReferenceStatement:
              Arn: !GetAtt ThreatIntelWAFv2IPBlacklist.Arn
  ALBWAFv2Association:
    Type: AWS::WAFv2::WebACLAssociation
    Properties: 
      ResourceArn: !Ref ApplicationLoadBalancerArn
      WebACLArn: !GetAtt WAFv2WebACL.Arn
  WAFLoggingBucket:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'syntheticsun-waf-logs-${AWS::AccountId}'
      AccessControl: Private
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
  WAFLoggingDeliveryStream:
    Type: AWS::KinesisFirehose::DeliveryStream
    Properties:
      DeliveryStreamName: aws-waf-logs-syntheticsun
      S3DestinationConfiguration:
        BucketARN: !GetAtt WAFLoggingBucket.Arn
        BufferingHints:
          IntervalInSeconds: 60
          SizeInMBs: 5
        CompressionFormat: UNCOMPRESSED
        Prefix: syntheticsun
        RoleARN: !GetAtt WAFLoggingDeliveryStreamRole.Arn
  WAFLoggingDeliveryStreamRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
          - Sid: firehosetrust
            Effect: Allow
            Principal:
              Service: firehose.amazonaws.com
            Action: sts:AssumeRole
            Condition:
              StringEquals:
                sts:ExternalId: !Sub '${AWS::AccountId}'
  WAFLoggingDeliveryStreamRolePolicy:
    Type: AWS::IAM::Policy
    Properties:
      PolicyName: Firehose-WAFLog-SyntheticSun-Policy
      PolicyDocument:
        Version: 2012-10-17
        Statement:
          - Effect: Allow
            Action:
              - s3:AbortMultipartUpload
              - s3:GetBucketLocation
              - s3:GetObject
              - s3:ListBucket
              - s3:ListBucketMultipartUploads
              - s3:PutObject
            Resource:
              - !Join 
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref WAFLoggingBucket
              - !Join 
                - ''
                - - 'arn:aws:s3:::'
                  - !Ref WAFLoggingBucket
                  - '*'
      Roles: 
        - !Ref WAFLoggingDeliveryStreamRole
  MISPInstance:
    Type: AWS::EC2::Instance
    Properties:
      IamInstanceProfile: !Ref MISPInstanceProfile
      DisableApiTermination: true
      ImageId: !Ref MISPAmiId
      KeyName: !Ref Ec2KeyPair
      InstanceType: !Ref MISPInstanceTypeParameter
      NetworkInterfaces:
        - AssociatePublicIpAddress: true
          DeleteOnTermination: true
          SubnetId: 
            !Ref PublicSubnetId
          DeviceIndex: 0
          GroupSet:
            - !Ref MISPSecGroup
      Tags: 
        - 
          Key: Name
          Value: SyntheticSun-MISP-Instance
  MISPInstanceProfileRole:
    Type: AWS::IAM::Role
    Properties:
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/AmazonSSMManagedInstanceCore
        - arn:aws:iam::aws:policy/CloudWatchAgentAdminPolicy
      RoleName: SyntheticSun-MISP-Role
      Policies:
      - PolicyName: SyntheticSun-MISP-RolePolicy
        PolicyDocument:
          Version: 2012-10-17
          Statement:
          - Effect: Allow
            Action:
              - s3:HeadBucket
              - s3:HeadObject 
              - s3:ListBucket
              - s3:GetObject
              - s3:GetObjectVersion
              - s3:PutObject
              - s3:PutObjectAcl
            Resource:
              - !Sub 'arn:aws:s3:::${SyntheticSunArtifacts}'
              - !Sub 'arn:aws:s3:::${SyntheticSunArtifacts}/*'
      AssumeRolePolicyDocument:
        Version: 2012-10-17
        Statement:
        - Effect: Allow
          Principal: { Service: ec2.amazonaws.com }
          Action:
            - sts:AssumeRole
  MISPInstanceProfile:
    DependsOn: MISPInstanceProfileRole
    Type: AWS::IAM::InstanceProfile
    Properties: 
      InstanceProfileName: SyntheticSun-MISP-Role
      Roles: 
        - !Ref MISPInstanceProfileRole
  SyntheticSunArtifacts:
    Type: AWS::S3::Bucket
    Properties:
      BucketName: !Sub 'syntheticsun-artifacts-${AWS::AccountId}'
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
  SyntheticSunES:
    Type: AWS::Elasticsearch::Domain
    UpdatePolicy:
      EnableVersionUpgrade: true
    Properties:
      DomainName: syntheticsun-es
      ElasticsearchClusterConfig:
        DedicatedMasterEnabled: true
        InstanceCount: 2
        InstanceType: !Ref ESDataNodeInstanceType
        DedicatedMasterType: !Ref ESMasterNodeInstanceType
        DedicatedMasterCount: 3
      ElasticsearchVersion: !Ref ESVersion
      EncryptionAtRestOptions:
        Enabled: true
      EBSOptions:
        EBSEnabled: true
        VolumeSize: 25
        VolumeType: gp2
  SuricataDNSLogGrp: 
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: Suricata-DNS-Logs 
      RetentionInDays: 7
  SuricataNotDNSLogGrp: 
    Type: AWS::Logs::LogGroup
    Properties:
      LogGroupName: Suricata-Not-DNS-Logs 
      RetentionInDays: 7
Outputs:
  WafArnOutput:
    Description: WAF Web ACL ARN
    Value: !GetAtt WAFv2WebACL.Arn
  FirehoseArnOutput:
    Description: Firehouse Delivery Stream ARN
    Value: !GetAtt WAFLoggingDeliveryStream.Arn
  ElasticsearchUrlOuput:
    Description: Elasticsearch Service domain endpoint URL
    Value: !GetAtt SyntheticSunES.DomainEndpoint